spring.application.name=expresofast-backend

# H2 en memoria: los datos se reinician cada vez que se apaga el servidor
spring.datasource.url=jdbc:h2:mem:expresofast;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
